name: FixProxyJoin
main: base.MainFPJ
version: 1
author: Zorotex
description:
website: https://zorotex.org
commands:
   fpj:
      description: Команда для ввода ip-адреса.
      usage: /<fpj> [ip]
      permission: <plugin name>.fpj
      permission-message: Нет разрешения <permission>